spring:
  application:
    name: dialog
  datasource:
    url: jdbc:postgresql://citus-master:5432/app
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: ${APP_JWT_SECRET:fgaqw342rvq3453dfgawer2342ef23f23f}
    ttl-minutes: ${APP_JWT_TTL_MINUTES:60}

server:
  port: 8080