services:
  db:
    image: postgres:18.1
    container_name: app-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./core/docker/db/init:/docker-entrypoint-initdb.d:ro
      - ./core/docker/db/dump:/dump:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20
  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    container_name: core-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      APP_REDIS_USER_INFO_WARMUP_ENABLED: ${APP_REDIS_USER_INFO_WARMUP_ENABLED:-false}
      APP_REDIS_USER_INFO_WARMUP_BATCH_SIZE: ${APP_REDIS_USER_INFO_WARMUP_BATCH_SIZE:-1000}
    ports:
      - "8081:8080"

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8082:8080"

  #redis:
    #image: redis:7
    #container_name: redis
    #ports:
      #- "6379:6379"
    #volumes:
      #- redis_data:/data

volumes:
  pgdata:
  redis_data:
  healthcheck-volume:
