spring:
  application:
    name: app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:ghwnj4l5kjtbnw}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
app:
  jwt:
    secret: ${APP_JWT_SECRET:fgaqw342rvq3453dfgawer2342ef23f23f}
    ttl-minutes: ${APP_JWT_TTL_MINUTES:60}

  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:25432/postgres
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 3000
        validation-timeout: 2000
        maximum-pool-size: 10
        minimum-idle: 2
        max-lifetime: 30000
    read:
      jdbc-url: jdbc:postgresql://localhost:35432/postgres
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 3000
        validation-timeout: 2000
        maximum-pool-size: 10
        minimum-idle: 2
        max-lifetime: 30000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true