global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: dialog-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - dialog:8080
