spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: post-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: social.network.app.dto
        spring.json.value.default.type: social.network.app.dto.PostDto
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual_immediate
  application:
    name: core
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:ghwnj4l5kjtbnw}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
app:
  kafka:
    topic:
      post-create:
        group-id: post-service-group
        name: app_post_create
      post-delete:
        name: app_post_delete
  jwt:
    secret: ${APP_JWT_SECRET:fgaqw342rvq3453dfgawer2342ef23f23f}
    ttl-minutes: ${APP_JWT_TTL_MINUTES:60}
  redis:
    user-info-cache:
      warmup-enabled: false
      warmup-batch-size: ${APP_REDIS_USER_INFO_WARMUP_BATCH_SIZE:1000}
  datasource:
    write:
      jdbc-url: ${APP_DATASOURCE_WRITE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}}
      username: ${APP_DATASOURCE_WRITE_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}
      password: ${APP_DATASOURCE_WRITE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:ghwnj4l5kjtbnw}}
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 3000
        validation-timeout: 2000
        maximum-pool-size: 10
        minimum-idle: 2
        max-lifetime: 30000
    read:
      jdbc-url: ${APP_DATASOURCE_READ_URL:${APP_DATASOURCE_WRITE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}}}
      username: ${APP_DATASOURCE_READ_USERNAME:${APP_DATASOURCE_WRITE_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}}
      password: ${APP_DATASOURCE_READ_PASSWORD:${APP_DATASOURCE_WRITE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:ghwnj4l5kjtbnw}}}
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 3000
        validation-timeout: 2000
        maximum-pool-size: 10
        minimum-idle: 2
        max-lifetime: 30000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8081
